# version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin # user
      POSTGRES_PASSWORD: admin # password
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata:Z
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - wbEndpointApp
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./pgdata
networks:
  wbEndpointApp:
    driver: bridge